/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HoverInfoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/i18n.ts
var en = {
  // Settings - sections
  "settings.folderHover": "Folder Hover",
  "settings.fileHover": "File Hover",
  "settings.style": "Style",
  // Settings - folder
  "settings.showFolderStats": "Show folder file count",
  "settings.showFolderStats.desc": "Show the number of files inside a folder when hovering over it.",
  "settings.showSubfolderCount": "Show subfolder count",
  "settings.showSubfolderCount.desc": "Also show the number of subfolders inside the folder.",
  "settings.showMarkdownOnly": "Count markdown files only",
  "settings.showMarkdownOnly.desc": "Only count .md files. When disabled, all file types are counted.",
  // Settings - file
  "settings.showFileSummary": "Show file summary",
  "settings.showFileSummary.desc": "Show a summary tooltip when hovering over a file.",
  "settings.showTags": "Show tags",
  "settings.showTags.desc": "Display frontmatter and inline tags in the tooltip.",
  "settings.showWordCount": "Show word count",
  "settings.showWordCount.desc": "Display the word count of the file (requires reading file content).",
  "settings.showCreatedDate": "Show created date",
  "settings.showCreatedDate.desc": "Display the file creation date.",
  "settings.showModifiedDate": "Show modified date",
  "settings.showModifiedDate.desc": "Display the file last-modified date.",
  "settings.showFirstHeading": "Show first heading",
  "settings.showFirstHeading.desc": "Display the first heading from the file as the title.",
  "settings.maxSummaryLength": "Max summary length",
  "settings.maxSummaryLength.desc": "Maximum number of characters for the description/summary text.",
  "settings.tooltipDelay": "Tooltip delay (ms)",
  "settings.tooltipDelay.desc": "Delay before the tooltip appears after hovering (in milliseconds).",
  "settings.maxWidth": "Max tooltip width (px)",
  "settings.maxWidth.desc": "Maximum width of the tooltip in pixels.",
  "settings.customCSS": "Custom CSS",
  "settings.customCSS.desc": "Custom CSS to apply to the tooltip. Use .hover-info-tooltip as the selector.",
  // Settings - language
  "settings.language": "Language",
  "settings.language.desc": "Interface language for the plugin.",
  // Tooltip - folder
  "tooltip.markdownFile": "markdown file",
  "tooltip.markdownFile_plural": "markdown files",
  "tooltip.file": "file",
  "tooltip.file_plural": "files",
  "tooltip.markdown": "markdown",
  "tooltip.subfolder": "subfolder",
  "tooltip.subfolder_plural": "subfolders",
  // Tooltip - file
  "tooltip.words": "words",
  "tooltip.created": "Created",
  "tooltip.modified": "Modified",
  // Dates
  "date.today": "Today",
  "date.yesterday": "Yesterday",
  "date.daysAgo": "days ago"
};
var zhCN = {
  // Settings - sections
  "settings.folderHover": "\u6587\u4EF6\u5939\u60AC\u505C",
  "settings.fileHover": "\u6587\u4EF6\u60AC\u505C",
  "settings.style": "\u6837\u5F0F",
  // Settings - folder
  "settings.showFolderStats": "\u663E\u793A\u6587\u4EF6\u5939\u6587\u4EF6\u6570\u91CF",
  "settings.showFolderStats.desc": "\u9F20\u6807\u60AC\u505C\u5728\u6587\u4EF6\u5939\u4E0A\u65F6\u663E\u793A\u5305\u542B\u7684\u6587\u4EF6\u6570\u91CF\u3002",
  "settings.showSubfolderCount": "\u663E\u793A\u5B50\u6587\u4EF6\u5939\u6570\u91CF",
  "settings.showSubfolderCount.desc": "\u540C\u65F6\u663E\u793A\u6587\u4EF6\u5939\u5185\u7684\u5B50\u6587\u4EF6\u5939\u6570\u91CF\u3002",
  "settings.showMarkdownOnly": "\u4EC5\u7EDF\u8BA1 Markdown \u6587\u4EF6",
  "settings.showMarkdownOnly.desc": "\u4EC5\u7EDF\u8BA1 .md \u6587\u4EF6\u3002\u5173\u95ED\u65F6\u5C06\u7EDF\u8BA1\u6240\u6709\u7C7B\u578B\u6587\u4EF6\u3002",
  // Settings - file
  "settings.showFileSummary": "\u663E\u793A\u6587\u4EF6\u6458\u8981",
  "settings.showFileSummary.desc": "\u9F20\u6807\u60AC\u505C\u5728\u6587\u4EF6\u4E0A\u65F6\u663E\u793A\u6458\u8981\u4FE1\u606F\u3002",
  "settings.showTags": "\u663E\u793A\u6807\u7B7E",
  "settings.showTags.desc": "\u5728\u63D0\u793A\u6846\u4E2D\u663E\u793A frontmatter \u548C\u5185\u8054\u6807\u7B7E\u3002",
  "settings.showWordCount": "\u663E\u793A\u5B57\u6570",
  "settings.showWordCount.desc": "\u663E\u793A\u6587\u4EF6\u7684\u5B57\u6570\u7EDF\u8BA1\uFF08\u9700\u8981\u8BFB\u53D6\u6587\u4EF6\u5185\u5BB9\uFF09\u3002",
  "settings.showCreatedDate": "\u663E\u793A\u521B\u5EFA\u65E5\u671F",
  "settings.showCreatedDate.desc": "\u663E\u793A\u6587\u4EF6\u7684\u521B\u5EFA\u65E5\u671F\u3002",
  "settings.showModifiedDate": "\u663E\u793A\u4FEE\u6539\u65E5\u671F",
  "settings.showModifiedDate.desc": "\u663E\u793A\u6587\u4EF6\u7684\u6700\u540E\u4FEE\u6539\u65E5\u671F\u3002",
  "settings.showFirstHeading": "\u663E\u793A\u9996\u4E2A\u6807\u9898",
  "settings.showFirstHeading.desc": "\u663E\u793A\u6587\u4EF6\u4E2D\u7684\u7B2C\u4E00\u4E2A\u6807\u9898\u4F5C\u4E3A\u6458\u8981\u6807\u9898\u3002",
  "settings.maxSummaryLength": "\u6458\u8981\u6700\u5927\u957F\u5EA6",
  "settings.maxSummaryLength.desc": "\u63CF\u8FF0/\u6458\u8981\u6587\u672C\u7684\u6700\u5927\u5B57\u7B26\u6570\u3002",
  "settings.tooltipDelay": "\u63D0\u793A\u6846\u5EF6\u8FDF (\u6BEB\u79D2)",
  "settings.tooltipDelay.desc": "\u9F20\u6807\u60AC\u505C\u540E\u63D0\u793A\u6846\u51FA\u73B0\u7684\u5EF6\u8FDF\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09\u3002",
  "settings.maxWidth": "\u63D0\u793A\u6846\u6700\u5927\u5BBD\u5EA6 (\u50CF\u7D20)",
  "settings.maxWidth.desc": "\u63D0\u793A\u6846\u7684\u6700\u5927\u5BBD\u5EA6\uFF08\u50CF\u7D20\uFF09\u3002",
  "settings.customCSS": "\u81EA\u5B9A\u4E49 CSS",
  "settings.customCSS.desc": "\u5E94\u7528\u4E8E\u63D0\u793A\u6846\u7684\u81EA\u5B9A\u4E49 CSS\u3002\u4F7F\u7528 .hover-info-tooltip \u4F5C\u4E3A\u9009\u62E9\u5668\u3002",
  // Settings - language
  "settings.language": "\u8BED\u8A00",
  "settings.language.desc": "\u63D2\u4EF6\u7684\u754C\u9762\u8BED\u8A00\u3002",
  // Tooltip - folder
  "tooltip.markdownFile": "\u4E2A Markdown \u6587\u4EF6",
  "tooltip.markdownFile_plural": "\u4E2A Markdown \u6587\u4EF6",
  "tooltip.file": "\u4E2A\u6587\u4EF6",
  "tooltip.file_plural": "\u4E2A\u6587\u4EF6",
  "tooltip.markdown": "\u4E2A Markdown",
  "tooltip.subfolder": "\u4E2A\u5B50\u6587\u4EF6\u5939",
  "tooltip.subfolder_plural": "\u4E2A\u5B50\u6587\u4EF6\u5939",
  // Tooltip - file
  "tooltip.words": "\u5B57",
  "tooltip.created": "\u521B\u5EFA",
  "tooltip.modified": "\u4FEE\u6539",
  // Dates
  "date.today": "\u4ECA\u5929",
  "date.yesterday": "\u6628\u5929",
  "date.daysAgo": "\u5929\u524D"
};
var locales = { en, "zh-cn": zhCN };
function getLocale(lang) {
  return locales[lang] || locales["en"];
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  language: "zh-cn",
  showFolderStats: true,
  showSubfolderCount: true,
  showMarkdownOnly: false,
  showFileSummary: true,
  showTags: true,
  showWordCount: false,
  showCreatedDate: false,
  showModifiedDate: true,
  showFirstHeading: true,
  maxSummaryLength: 100,
  tooltipDelay: 300,
  customCSS: "",
  maxWidth: 300
};
var HoverInfoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const t = getLocale(this.plugin.settings.language);
    containerEl.createEl("h2", { text: t["settings.language"] });
    new import_obsidian.Setting(containerEl).setName(t["settings.language"]).setDesc(t["settings.language.desc"]).addDropdown(
      (dropdown) => dropdown.addOption("zh-cn", "\u7B80\u4F53\u4E2D\u6587").addOption("en", "English").setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    containerEl.createEl("h2", { text: t["settings.folderHover"] });
    new import_obsidian.Setting(containerEl).setName(t["settings.showFolderStats"]).setDesc(t["settings.showFolderStats.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showFolderStats).onChange(async (value) => {
        this.plugin.settings.showFolderStats = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showSubfolderCount"]).setDesc(t["settings.showSubfolderCount.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showSubfolderCount).onChange(async (value) => {
        this.plugin.settings.showSubfolderCount = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showMarkdownOnly"]).setDesc(t["settings.showMarkdownOnly.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showMarkdownOnly).onChange(async (value) => {
        this.plugin.settings.showMarkdownOnly = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: t["settings.fileHover"] });
    new import_obsidian.Setting(containerEl).setName(t["settings.showFileSummary"]).setDesc(t["settings.showFileSummary.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showFileSummary).onChange(async (value) => {
        this.plugin.settings.showFileSummary = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showTags"]).setDesc(t["settings.showTags.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showTags).onChange(async (value) => {
        this.plugin.settings.showTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showWordCount"]).setDesc(t["settings.showWordCount.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showWordCount).onChange(async (value) => {
        this.plugin.settings.showWordCount = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showCreatedDate"]).setDesc(t["settings.showCreatedDate.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCreatedDate).onChange(async (value) => {
        this.plugin.settings.showCreatedDate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showModifiedDate"]).setDesc(t["settings.showModifiedDate.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showModifiedDate).onChange(async (value) => {
        this.plugin.settings.showModifiedDate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.showFirstHeading"]).setDesc(t["settings.showFirstHeading.desc"]).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showFirstHeading).onChange(async (value) => {
        this.plugin.settings.showFirstHeading = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t["settings.maxSummaryLength"]).setDesc(t["settings.maxSummaryLength.desc"]).addText(
      (text) => text.setValue(String(this.plugin.settings.maxSummaryLength)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxSummaryLength = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h2", { text: t["settings.style"] });
    new import_obsidian.Setting(containerEl).setName(t["settings.tooltipDelay"]).setDesc(t["settings.tooltipDelay.desc"]).addText((text) => {
      text.setValue(String(this.plugin.settings.tooltipDelay)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.tooltipDelay = num;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.setAttribute("min", "0");
      text.inputEl.setAttribute("step", "50");
    });
    new import_obsidian.Setting(containerEl).setName(t["settings.maxWidth"]).setDesc(t["settings.maxWidth.desc"]).addText((text) => {
      text.setValue(String(this.plugin.settings.maxWidth)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxWidth = num;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.setAttribute("min", "100");
      text.inputEl.setAttribute("step", "10");
    });
    new import_obsidian.Setting(containerEl).setName(t["settings.customCSS"]).setDesc(t["settings.customCSS.desc"]).addTextArea((text) => {
      text.setValue(this.plugin.settings.customCSS).onChange(async (value) => {
        this.plugin.settings.customCSS = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 5;
      text.inputEl.cols = 40;
      text.inputEl.style.fontFamily = "monospace";
      text.inputEl.style.fontSize = "12px";
    });
  }
};

// src/hover.ts
var import_obsidian3 = require("obsidian");

// src/summary.ts
var import_obsidian2 = require("obsidian");
function getFolderStats(folder, markdownOnly) {
  let fileCount = 0;
  let mdCount = 0;
  let folderCount = 0;
  for (const child of folder.children) {
    if (child instanceof import_obsidian2.TFolder) {
      folderCount++;
      const sub = getFolderStats(child, markdownOnly);
      fileCount += sub.fileCount;
      mdCount += sub.mdCount;
      folderCount += sub.folderCount;
    } else if (child instanceof import_obsidian2.TFile) {
      fileCount++;
      if (child.extension === "md") {
        mdCount++;
      }
    }
  }
  return { fileCount, mdCount, folderCount };
}
async function getFileSummary(app, file, options) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  let description = null;
  if (cache == null ? void 0 : cache.frontmatter) {
    description = cache.frontmatter["description"] || cache.frontmatter["summary"] || cache.frontmatter["desc"] || null;
    if (description && typeof description !== "string") {
      description = String(description);
    }
    if (description && description.length > options.maxSummaryLength) {
      description = description.slice(0, options.maxSummaryLength) + "\u2026";
    }
  }
  const tags = [];
  if (options.showTags) {
    if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) {
      const ftags = cache.frontmatter.tags;
      if (Array.isArray(ftags)) {
        for (const t of ftags) {
          tags.push(typeof t === "string" ? t : String(t));
        }
      } else if (typeof ftags === "string") {
        tags.push(ftags);
      }
    }
    if (cache == null ? void 0 : cache.tags) {
      for (const t of cache.tags) {
        const tag = t.tag.startsWith("#") ? t.tag : "#" + t.tag;
        if (!tags.includes(tag)) {
          tags.push(tag);
        }
      }
    }
  }
  const firstHeading = (cache == null ? void 0 : cache.headings) && cache.headings.length > 0 ? cache.headings[0].heading : null;
  let wordCount = null;
  if (options.showWordCount) {
    try {
      const content = await app.vault.cachedRead(file);
      wordCount = content.split(/\s+/).filter((w) => w.length > 0).length;
    } catch (e) {
      wordCount = null;
    }
  }
  return {
    description,
    tags,
    wordCount,
    created: file.stat.ctime,
    modified: file.stat.mtime,
    size: file.stat.size,
    firstHeading
  };
}

// src/hover.ts
var HoverManager = class {
  constructor(app, settings) {
    this.tooltip = null;
    this.hoverTimer = null;
    this.currentTarget = null;
    this.observer = null;
    this.app = app;
    this.settings = settings;
    this.boundHandler = this.handleMouseOver.bind(this);
  }
  /** Get current locale dictionary based on plugin language setting. */
  t() {
    return getLocale(this.settings.language);
  }
  /**
   * Attach hover listeners to the file explorer.
   * Uses event delegation on document body, filtered by nav selectors.
   */
  attach() {
    document.body.addEventListener("mouseover", this.boundHandler, true);
    document.body.addEventListener(
      "mouseout",
      this.handleMouseOut.bind(this),
      true
    );
  }
  /**
   * Remove all listeners and clean up DOM.
   */
  detach() {
    document.body.removeEventListener("mouseover", this.boundHandler, true);
    document.body.removeEventListener(
      "mouseout",
      this.handleMouseOut.bind(this),
      true
    );
    this.removeTooltip();
    if (this.hoverTimer !== null) {
      clearTimeout(this.hoverTimer);
      this.hoverTimer = null;
    }
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
  }
  /**
   * Update settings reference (called after settings change).
   */
  updateSettings(settings) {
    this.settings = settings;
  }
  handleMouseOver(event) {
    const target = event.target;
    const folderTitle = target.closest(".nav-folder-title");
    const fileTitle = target.closest(".nav-file-title");
    const el = folderTitle || fileTitle;
    if (!el) {
      this.cancelHover();
      return;
    }
    if (el === this.currentTarget)
      return;
    this.currentTarget = el;
    this.removeTooltip();
    if (this.hoverTimer !== null)
      clearTimeout(this.hoverTimer);
    this.hoverTimer = window.setTimeout(() => {
      if (el === this.currentTarget) {
        if (folderTitle) {
          this.showFolderTooltip(event, folderTitle);
        } else if (fileTitle) {
          this.showFileTooltip(event, fileTitle);
        }
      }
    }, this.settings.tooltipDelay);
  }
  handleMouseOut(event) {
    const target = event.target;
    const folderTitle = target.closest(".nav-folder-title");
    const fileTitle = target.closest(".nav-file-title");
    if (folderTitle || fileTitle) {
      const related = event.relatedTarget;
      if (related && related.closest(".hover-info-tooltip"))
        return;
      this.cancelHover();
      this.removeTooltip();
    }
  }
  cancelHover() {
    this.currentTarget = null;
    if (this.hoverTimer !== null) {
      clearTimeout(this.hoverTimer);
      this.hoverTimer = null;
    }
  }
  showFolderTooltip(event, el) {
    if (!this.settings.showFolderStats)
      return;
    const dataPath = el.getAttribute("data-path");
    if (!dataPath)
      return;
    const folder = this.app.vault.getAbstractFileByPath(dataPath);
    if (!(folder instanceof import_obsidian3.TFolder))
      return;
    const stats = getFolderStats(folder, this.settings.showMarkdownOnly);
    const t = this.t();
    const lines = [];
    if (this.settings.showMarkdownOnly) {
      lines.push(`${stats.mdCount} ${t["tooltip.markdownFile"]}`);
    } else {
      lines.push(`${stats.fileCount} ${t["tooltip.file"]}`);
      if (stats.mdCount > 0 && stats.mdCount !== stats.fileCount) {
        lines.push(`${stats.mdCount} ${t["tooltip.markdown"]}`);
      }
    }
    if (this.settings.showSubfolderCount && stats.folderCount > 0) {
      lines.push(`${stats.folderCount} ${t["tooltip.subfolder"]}`);
    }
    this.renderTooltip(event, lines.join(" \xB7 "));
  }
  async showFileTooltip(event, el) {
    if (!this.settings.showFileSummary)
      return;
    const dataPath = el.getAttribute("data-path");
    if (!dataPath)
      return;
    const file = this.app.vault.getAbstractFileByPath(dataPath);
    if (!(file instanceof import_obsidian3.TFile))
      return;
    const summary = await getFileSummary(this.app, file, {
      showTags: this.settings.showTags,
      showWordCount: this.settings.showWordCount,
      maxSummaryLength: this.settings.maxSummaryLength
    });
    const t = this.t();
    const lines = [];
    if (this.settings.showFirstHeading && summary.firstHeading) {
      lines.push(`**${escapeHtml(summary.firstHeading)}**`);
    }
    if (summary.description) {
      lines.push(escapeHtml(summary.description));
    }
    if (this.settings.showTags && summary.tags.length > 0) {
      lines.push(
        summary.tags.map((tag) => `<span class="hover-info-tag">${escapeHtml(tag)}</span>`).join(" ")
      );
    }
    const meta = [];
    if (this.settings.showWordCount && summary.wordCount !== null) {
      meta.push(`${summary.wordCount} ${t["tooltip.words"]}`);
    }
    if (this.settings.showCreatedDate && summary.created) {
      meta.push(`${t["tooltip.created"]}: ${formatDate(summary.created, t)}`);
    }
    if (this.settings.showModifiedDate && summary.modified) {
      meta.push(
        `${t["tooltip.modified"]}: ${formatDate(summary.modified, t)}`
      );
    }
    if (meta.length > 0) {
      lines.push(`<span class="hover-info-meta">${meta.join(" \xB7 ")}</span>`);
    }
    if (lines.length > 0) {
      this.renderTooltip(event, lines.join("<br>"));
    }
  }
  renderTooltip(event, html) {
    this.removeTooltip();
    const tooltip = document.body.createDiv("hover-info-tooltip");
    tooltip.innerHTML = html;
    if (this.settings.customCSS) {
      const styleEl = tooltip.createEl("style");
      styleEl.textContent = this.settings.customCSS;
    }
    this.positionTooltip(tooltip, event.clientX, event.clientY);
    document.body.appendChild(tooltip);
    this.tooltip = tooltip;
    const moveHandler = (e) => {
      this.positionTooltip(tooltip, e.clientX, e.clientY);
    };
    tooltip.addEventListener("mousemove", moveHandler);
    tooltip.addEventListener("mouseleave", () => {
      this.removeTooltip();
    });
  }
  positionTooltip(tooltip, mouseX, mouseY) {
    const offset = 12;
    const maxWidth = this.settings.maxWidth;
    tooltip.style.maxWidth = `${maxWidth}px`;
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const rect = tooltip.getBoundingClientRect();
    const tw = rect.width || maxWidth;
    const th = rect.height || 100;
    let left = mouseX + offset;
    let top = mouseY + offset;
    if (left + tw > vw - 10) {
      left = mouseX - tw - offset;
      if (left < 10)
        left = 10;
    }
    if (top + th > vh - 10) {
      top = mouseY - th - offset;
      if (top < 10)
        top = 10;
    }
    tooltip.style.left = `${left}px`;
    tooltip.style.top = `${top}px`;
  }
  removeTooltip() {
    if (this.tooltip) {
      this.tooltip.remove();
      this.tooltip = null;
    }
  }
};
function escapeHtml(text) {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}
function formatDate(timestamp, t) {
  const date = new Date(timestamp);
  const now = /* @__PURE__ */ new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1e3 * 60 * 60 * 24));
  if (diffDays === 0) {
    return t["date.today"] + " " + date.toLocaleTimeString(void 0, {
      hour: "2-digit",
      minute: "2-digit"
    });
  } else if (diffDays === 1) {
    return t["date.yesterday"] + " " + date.toLocaleTimeString(void 0, {
      hour: "2-digit",
      minute: "2-digit"
    });
  } else if (diffDays < 7) {
    return `${diffDays} ${t["date.daysAgo"]}`;
  } else {
    return date.toLocaleDateString(void 0, {
      year: "numeric",
      month: "short",
      day: "numeric"
    });
  }
}

// src/main.ts
var HoverInfoPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.hoverManager = null;
  }
  async onload() {
    await this.loadSettings();
    this.hoverManager = new HoverManager(this.app, this.settings);
    this.hoverManager.attach();
    this.addSettingTab(new HoverInfoSettingTab(this.app, this));
  }
  onunload() {
    if (this.hoverManager) {
      this.hoverManager.detach();
      this.hoverManager = null;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.hoverManager) {
      this.hoverManager.updateSettings(this.settings);
    }
  }
};
